var math_data = [
    {"name": "Addition",
     "text": "Fill in the empty box",
     "template": "$0 + $1 = #",
     "range": [3, 8],
     "image": "img/maths/add.jpg",
     "equation": "Q[0] + Q[1] == A[0]",
     "answer": "Q[0] + Q[1]",
     "level": 1},

    {"name": "Subtraction",
     "text": "Fill in the empty box",
     "template": "$0 - $1 = #",
     "range": [3, 8],
     "image": "img/maths/subtract.jpg",
     "equation": "Q[0] - Q[1] == A[0]",
     "answer": "Q[0] - Q[1]",
     "level": 1},

    {"name": "Multiplication",
     "text": "Fill in the empty box",
     "template": "$0 x $1 = #",
     "range": [3, 8],
     "image": "img/maths/multiply.jpg",
     "equation": "Q[0] * Q[1] == A[0]",
     "answer": "Q[0] * Q[1]",
     "level": 1},

    {"name": "Mixed signs, addition and subtraction",
     "text": "Fill in the empty box",
     "template": "$0 + $1 - $2 + $3 = #",
     "range": [3, 5],
     "image": "img/maths/subtract.jpg",
     "equation": "Q[0] + Q[1] - Q[2] + Q[3] == A[0]",
     "answer": "Q[0] + Q[1] - Q[2] + Q[3]",
     "level": 1},

    {"name": "Mixed signs, addition and subtraction",
     "text": "Fill in the empty box",
     "template": "$0 - $1 + $2 - $3 = #",
     "range": [3, 5],
     "image": "img/maths/add.jpg",
     "equation": "Q[0] - Q[1] + Q[2] - Q[3] == A[0]",
     "answer": "Q[0] - Q[1] + Q[2] - Q[3]",
     "level": 1},

    {"name": "Mixed signs, addition and multiplication",
     "text": "Fill in the empty box",
     "template": "$0 + $1 x $2 = #",
     "range": [3, 6],
     "image": "img/maths/multiply.jpg",
     "equation": "Q[0] + Q[1] * Q[2] == A[0]",
     "answer": "Q[0] + Q[1] * Q[2]",
     "level": 1},

    {"name": "Mixed signs, subtraction and multiplication",
     "text": "Fill in the empty box",
     "template": "$0 - $1 x $2 = #",
     "range": [3, 6],
     "image": "img/maths/multiply.jpg",
     "equation": "Q[0] - Q[1] * Q[2] == A[0]",
     "answer": "Q[0] + Q[1] * Q[2]",
     "level": 1},

    {"name": "Mixed signs, multiplication and addition",
     "text": "Fill in the empty box",
     "template": "$0 x $1 + $2 = #",
     "range": [3, 6],
     "image": "img/maths/add.jpg",
     "equation": "Q[0] * Q[1] + Q[2] == A[0]",
     "answer": "Q[0] * Q[1] + Q[2]",
     "level": 1},

    {"name": "Mixed signs, multiplication and subtraction",
     "text": "Fill in the empty box",
     "template": "$0 x $1 - $2 = #",
     "range": [3, 6],
     "image": "img/maths/multiply.jpg",
     "equation": "Q[0] * Q[1] - Q[2] == A[0]",
     "answer": "Q[0] * Q[1] - Q[2]",
     "level": 1},

    {"name": "Area of a rectangle",
     "text": "What is the area of the given rectangle?",
     "template": "Height = $0 cm<br>Width = $1 cm<br>Area = # cm<sup>2</sup>",
     "range": [3, 8],
     "image": "img/maths/rectangle_area.jpg",
     "equation": "Q[0] * Q[1] == A[0]",
     "answer": "Q[0] * Q[1]",
     "level": 1},

    {"name": "Perimeter of a rectangle",
     "text": "What is the perimeter of the given rectangle?",
     "template": "Height = $0 cm<br>Width = $1 cm<br>Perimeter = # cm",
     "range": [3, 8],
     "image": "img/maths/rectangle_perimeter.jpg",
     "equation": "(2 * Q[0]) + (2 * Q[1]) == A[0]",
     "answer": "(2 * Q[0]) + (2 * Q[1])",
     "level": 1},

    {"name": "Area of a square",
     "text": "What is the area of the given square?",
     "template": "Side length = $0 cm<br>Area = # cm<sup>2</sup>",
     "range": [3, 8],
     "image": "img/maths/square_area.jpg",
     "equation": "Q[0] * Q[0] == A[0]",
     "answer": "Q[0] * Q[1]",
     "level": 1},

    {"name": "Perimeter of a square",
     "text": "What is the perimeter of the given square?",
     "template": "Side length = $0 cm<br>Perimeter = # cm",
     "range": [3, 8],
     "image": "img/maths/square_perimeter.jpg",
     "equation": "(4 * Q[0]) == A[0]",
     "answer": "(4 * Q[0])",
     "level": 1},

    // objects with the accuracy field have the accuracy var and the equationAnswer variable for an easier evaluation
    {"name": "Division (Accuracy to 3 decimal places)",
     "text": "Fill in the empty box",
     "template": "$0 / $1 = #",
     "range": [2, 8],
     "accuracy": 0.3,
     "image": "img/maths/division.jpg",
     "equation": "Q[0] / Q[1]",
     "equationAnswer": "A[0]",
     "answer": "Q[0] / Q[1]",
     "level": 2},

    {"name": "Addition",
     "text": "Fill in the empty box",
     "template": "$0 + # = $1",
     "range": [9, 72],
     "image": "img/maths/add.jpg",
     "equation": "Q[0] + A[0] == Q[1]",
     "answer": "Q[1] - Q[0]",
     "level": 2},

    {"name": "Subtraction",
     "text": "Fill in the empty box",
     "template": "$0 - # = $1",
     "range": [9, 72],
     "image": "img/maths/subtract.jpg",
     "equation": "Q[0] - A[0] == Q[1]",
     "answer": "-(Q[1] - Q[0])",
     "level": 2},

    {"name": "Multiplication (Accuracy to 3 decimal places)",
     "text": "Fill in the empty box",
     "template": "$0 x # = $1",
     "range": [2, 8],
     "accuracy": 0.3,
     "image": "img/maths/multiply.jpg",
     "equation": "Q[0] * A[0]",
     "equationAnswer": "Q[1]",
     "answer": "Q[1] / Q[0]",
     "level": 2},

    {"name": "Mixed signs, addition and subtraction",
     "text": "Fill in the empty box",
     "template": "# + $0 - # + $1 = $2",
     "range": [3, 5],
     "image": "img/maths/subtract.jpg",
     "equation": "A[0] + Q[0] - A[1] + Q[1] == Q[2]",
     "answer": "'Example answer: first number = 1, second number = ' + (1 + Q[0] + Q[1] - Q[2])",
     "level": 2}
];
